import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { basename, dirname, resolve } from "node:path";
import {
  catalogToPackSizes,
  dishFilesToLibrary,
  parseDishFile,
  parseIngredientCatalog,
  parseMenuHistory,
} from "../src/data/parse.js";
import {
  validateCatalogGroups,
  validateDishFiles,
  validateIngredientNamesResolve,
  validateMenuHistoryAgainstLibrary,
  validatePackSizesUsed,
} from "../src/data/validators.js";
import type {
  CatalogIngredient,
  Dish,
  DishFile,
  Ingredient,
  MenuHistoryRow,
  PackSizeHeader,
} from "../src/data/schemas.js";

/** Read every data/dishes/<slug>.md file, sorted by dish id for determinism. */
export function loadDishFiles(dishesDir: string): DishFile[] {
  const files: DishFile[] = [];
  for (const entry of readdirSync(dishesDir)) {
    if (!entry.endsWith(".md")) continue;
    const slug = basename(entry, ".md");
    files.push(parseDishFile(slug, readFileSync(resolve(dishesDir, entry), "utf8")));
  }
  files.sort((a, b) => a.dish.id - b.dish.id);
  return files;
}

interface BakeOutput {
  libraryPath: string;
  historyPath: string;
  dishCount: number;
  ingredientCount: number;
  packSizeCount: number;
  catalogCount: number;
  historyRowCount: number;
}

interface BakeOptions {
  dataDir: string;
  outDir: string;
}

function tsLiteral(value: unknown): string {
  return JSON.stringify(value);
}

function renderLibrary(
  dishes: Dish[],
  packSizes: PackSizeHeader[],
  ingredients: Ingredient[],
  catalog: CatalogIngredient[],
): string {
  return [
    "// Generated by engine/scripts/bake.ts from data/dishes/*.md + data/ingredients.md. Do not edit by hand.",
    "",
    "import type {",
    "  CatalogIngredient,",
    "  Dish,",
    "  Ingredient,",
    "  PackSizeHeader,",
    '} from "./schemas.js";',
    "",
    `export const dishes: Dish[] = ${tsLiteral(dishes)};`,
    "",
    `export const packSizes: PackSizeHeader[] = ${tsLiteral(packSizes)};`,
    "",
    `export const ingredients: Ingredient[] = ${tsLiteral(ingredients)};`,
    "",
    `export const catalog: CatalogIngredient[] = ${tsLiteral(catalog)};`,
    "",
    "export const library: {",
    "  dishes: Dish[];",
    "  packSizes: PackSizeHeader[];",
    "  ingredients: Ingredient[];",
    "  catalog: CatalogIngredient[];",
    "} = { dishes, packSizes, ingredients, catalog };",
    "",
  ].join("\n");
}

function renderHistory(rows: MenuHistoryRow[]): string {
  return [
    "// Generated by engine/scripts/bake.ts from data/menu_history.md. Do not edit by hand.",
    "",
    'import type { MenuHistoryRow } from "./schemas.js";',
    "",
    `export const history: MenuHistoryRow[] = ${tsLiteral(rows)};`,
    "",
  ].join("\n");
}

export function bake(options: BakeOptions): BakeOutput {
  const { dataDir, outDir } = options;

  const dishesDir = resolve(dataDir, "dishes");
  const ingredientsMd = readFileSync(resolve(dataDir, "ingredients.md"), "utf8");
  const historyMd = readFileSync(resolve(dataDir, "menu_history.md"), "utf8");

  const dishFiles = loadDishFiles(dishesDir);
  const catalog = parseIngredientCatalog(ingredientsMd);
  const history = parseMenuHistory(historyMd);

  const { dishes, ingredients } = dishFilesToLibrary(dishFiles);
  const packSizes = catalogToPackSizes(catalog);

  // Blocking data-integrity gates (feature plan §1.3 / §5). Any failure aborts
  // the bake before emitting, so CI fails loudly rather than baking bad data.
  validateDishFiles(dishFiles);
  validateCatalogGroups(catalog);
  validateIngredientNamesResolve(dishFiles, catalog);
  validatePackSizesUsed(packSizes, ingredients);
  validateMenuHistoryAgainstLibrary(history, dishes);

  const libraryPath = resolve(outDir, "library.ts");
  const historyPath = resolve(outDir, "history.ts");

  writeFileSync(libraryPath, renderLibrary(dishes, packSizes, ingredients, catalog));
  writeFileSync(historyPath, renderHistory(history));

  return {
    libraryPath,
    historyPath,
    dishCount: dishes.length,
    ingredientCount: ingredients.length,
    packSizeCount: packSizes.length,
    catalogCount: catalog.length,
    historyRowCount: history.length,
  };
}

function defaultPaths(): BakeOptions {
  const here = dirname(fileURLToPath(import.meta.url));
  // When compiled, this file lives at engine/dist/scripts/bake.js, so the
  // repo root is three levels up. Resolve the source dir for output (not the
  // dist mirror) so the emitted files land where the rest of the engine
  // imports them.
  const repoRoot = resolve(here, "../../..");
  return {
    dataDir: resolve(repoRoot, "data"),
    outDir: resolve(repoRoot, "engine/src/data"),
  };
}

function isEntrypoint(): boolean {
  if (!process.argv[1]) return false;
  try {
    return resolve(process.argv[1]) === fileURLToPath(import.meta.url);
  } catch {
    return false;
  }
}

if (isEntrypoint()) {
  try {
    const result = bake(defaultPaths());
    process.stdout.write(
      [
        `bake: wrote ${result.libraryPath}`,
        `bake: wrote ${result.historyPath}`,
        `bake: ${result.dishCount} dishes, ${result.catalogCount} catalog ingredients (${result.packSizeCount} tracked), ${result.ingredientCount} ingredient rows, ${result.historyRowCount} history rows`,
        "",
      ].join("\n"),
    );
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    process.stderr.write(`bake failed: ${message}\n`);
    process.exit(1);
  }
}
